-- 20260612000003_ponto_imediato.sql
-- Permite ponto de retirada do tipo 'imediato' (container dos itens balcão, sem destino).
--
-- Motivo: pedido_itens só se liga ao pedido via ponto_retirada_id (não há pedido_id no
-- item). Itens 'imediato' precisam, portanto, viver dentro de um ponto real — senão
-- viram órfãos e somem ao salvar/recarregar. Este ponto não tem empresa/endereço (o card
-- Destino não renderiza nada para ele); é só um container para reaproveitar a
-- persistência/carga que já são agnósticas ao tipo do ponto.
--
-- Nota de deploy (PG 12+/Supabase): ALTER TYPE ... ADD VALUE PODE rodar em transação; a
-- restrição real é não USAR o novo valor na MESMA transação que o adiciona — esta migração
-- só adiciona (não usa), então é segura via psql, `supabase db push` ou SQL Editor. Fica
-- standalone (sem BEGIN/COMMIT) por simplicidade. Aplicar ANTES do código que grava
-- tipo='imediato' (nuvem E hub), senão o INSERT falha com 'invalid input value for enum'.
ALTER TYPE public.ponto_retirada_destino ADD VALUE IF NOT EXISTS 'imediato';
